"""
This type stub file was generated by pyright.
"""

import sys
from tkinter import Misc
from tkinter.commondialog import Dialog
from typing import ClassVar

if sys.version_info >= (3, 9):
    ...
class Chooser(Dialog):
    command: ClassVar[str]
    ...


if sys.version_info >= (3, 9):
    def askcolor(color: str | bytes | None = ..., *, initialcolor: str = ..., parent: Misc = ..., title: str = ...) -> tuple[None, None] | tuple[tuple[int, int, int], str]:
        ...
    
else:
    ...
